### ISSUE TITLE
Add `"nolib": true` to jsx/tsconfig.json to use Adobe's native objects, not typescripts?

### ISSUE THREAD

**Issue by zlovatt** [fusepilot/parcel-plugin-cep-starter#1]
For example, Adobe's `File` object is different than the one from Typescript. In jsx, we want Adobe's.
Otherwise we get a tonne of issues about properties/methods not existing on default objects, whereas we know they do.

(Opening a ticket instead of a PR because it's possible this would have other repercussions outside of my awareness 😄)

**Comment by vespakoen** [comment]
Fixed in https://github.com/fusepilot/parcel-plugin-cep-starter/pull/4

**Comment by zlovatt** [comment]
Closed in #27
